In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('GA_2_dataset.csv')

In [ ]:
df = pd.DataFrame(data)
df

,PlayerID,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,EngagementLevel
0,35900,37.0,Male,Other,Strategy,23.929404,NaN,Hard,3,124,99,18,Medium
1,27085,25.0,Male,NaN,Action,22.755168,1.0,Easy,14,84,84,12,Medium
2,39595,24.0,Female,Europe,Simulation,19.505292,0.0,Hard,3,172,9,18,Medium
3,37440,26.0,Female,Europe,RPG,11.009645,NaN,NaN,3,83,36,43,Low
4,22882,17.0,Female,USA,RPG,0.581039,1.0,Medium,5,163,9,24,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,42828,22.0,Female,USA,Sports,21.336213,0.0,Medium,13,58,74,15,Medium
9996,18169,21.0,Male,Europe,Strategy,6.158520,0.0,Easy,4,10,77,27,Low
9997,22094,43.0,Male,USA,Action,22.628880,0.0,Easy,4,161,66,46,Medium
9998,42490,16.0,Male,Europe,Strategy,17.111949,0.0,Medium,6,70,24,32,Medium
9999,42839,45.0,Male,Other,Simulation,22.067866,1.0,Easy,4,131,10,24,Medium

<h1> Which of the following columns have object datatype?

In [ ]:
df.select_dtypes(include='object').columns

Index(['Gender', 'Location', 'GameGenre', 'GameDifficulty', 'EngagementLevel'], dtype='object')

<h2> In this dataset, how many "Males" from "Europe" have made "InGamePurchases" ?

In [ ]:
df.loc[(df['Gender']=='Male') & (df['Location']=='Europe') & df['InGamePurchases']>= 1.0].shape[0]

299

or

In [ ]:
df.groupby(['Gender','Location'])['InGamePurchases'].value_counts()

Gender  Location  InGamePurchases
Female  Asia      0.0                 528
                  1.0                 130
        Europe    0.0                 759
                  1.0                 212
        Other     0.0                 261
                  1.0                  68
        USA       0.0                1072
                  1.0                 248
Male    Asia      0.0                 823
                  1.0                 227
        Europe    0.0                1237
                  1.0                 299
        Other     0.0                 379
                  1.0                  92
        USA       0.0                1629
                  1.0                 424
Name: count, dtype: int64

<h2> In your dataset, how many players under the "Age" 18 have strictly greater than 10 "PlayTimeHours"?

In [ ]:
df.loc[(df['Age']<18) & (df['PlayTimeHours']>10)].shape[0]

453

<h2> Create feature matrix(X) and label vector(y) using following instructions:

"EngagementLevel" is the target column(y).

All the columns except the target column are in feature matrix(X).

How many total null values were present in the whole dataset ?

In [ ]:
X = df.drop('EngagementLevel', axis = 1)

In [ ]:
y = df['EngagementLevel']

In [ ]:
X.shape[1]

12

In [ ]:
df.isnull().sum().sum()

np.int64(3337)

<h2> Split the dataset into train dataset and test dataset in the following manner.

Use sklearn train_test_split function to split the data.

Use only 20% data as test_set and keep random_state = 42

Which category has the least value counts in y_train?

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
y_train.value_counts()

EngagementLevel
Medium    3983
Low       2021
High      1996
Name: count, dtype: int64

In [ ]:
# High

<h2> Common Instructions for Question 6 and 7

Rules for Imputing the missing(NaN) or Unknown values:

Calculating statistical values (such as mean, median, mode) for each column in the training dataset.

Applying these calculated statistical values to replace missing (NaN) and unknown values in both the training and test datasets.

Ensure that the calculation of statistical values excludes any rows containing missing or unknown values.

Replace Unknown values in the "Age" feature with the Mean value in that. Replace Unknown values in the "Location" feature with the constant value "Other".

Replace Unknown values in the "GameDifficulty" feature with the Most Frequent value in that.

Replace Unknown values in the "InGamePurchases" feature with the constant value '0'.

Write the answers related to the above imputation in below questions respectively.

In [ ]:
#Calculating statistical values (such as mean, median, mode) for each column in the training dataset.

mean_values = X_train.mean(numeric_only = True)
median_values = X_train.median(numeric_only = True)
mode_values = X_train.mode().iloc[0]

In [ ]:
# Applying these calculated statistical values to replace missing (NaN) and unknown values in both the training and test datasets.
# Ensure that the calculation of statistical values excludes any rows containing missing or unknown values.

X_train.isnull().sum()

PlayerID                       0
Age                          640
Gender                         0
Location                     639
GameGenre                      0
PlayTimeHours                  0
InGamePurchases              716
GameDifficulty               675
SessionsPerWeek                0
AvgSessionDurationMinutes      0
PlayerLevel                    0
AchievementsUnlocked           0
dtype: int64

In [177]:
# Replace Unknown values in the "Age" feature with the Mean value in that.
X_train['Age'] = X_train['Age'].fillna(mean_values['Age'])
X_test['Age'] = X_test['Age'].fillna(mean_values['Age'])

In [178]:
X_train['Location'] = X_train['Location'].fillna('Other')
X_test['Location'] = X_test['Location'].fillna('Other')

In [ ]:
from sklearn.impute import SimpleImputer

In [180]:
X_train['GameDifficulty'] = X_train['GameDifficulty'].fillna(mode_values['GameDifficulty'])
X_test['GameDifficulty'] = X_test['GameDifficulty'].fillna(mode_values['GameDifficulty'])

In [179]:
X_train['InGamePurchases'] = X_train['InGamePurchases'].fillna(0)
X_test['InGamePurchases'] = X_test['InGamePurchases'].fillna(0)

<h2> Write the sum of transformed(imputed) "Age" column of the test dataset . (upto 2 digits after decimal points)

In [ ]:
X_test['Age'].sum().round(2)

np.float64(63585.24)

<h2> Ques. 7

In [ ]:
#Drop PlayerId
X_train.drop(columns=['PlayerID'], inplace=True)
X_test.drop(columns=['PlayerID'], inplace=True)

In [ ]:
#Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()
X_train['GameDifficulty'] = oe.fit_transform(X_train[['GameDifficulty']])
X_test['GameDifficulty'] = oe.transform(X_test[['GameDifficulty']])

In [ ]:
#one hot encoding

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')
train_ohe = ohe.fit_transform(X_train[['Gender', 'Location', 'GameGenre']])
test_ohe = ohe.transform(X_test[['Gender', 'Location', 'GameGenre']])

In [ ]:
#Remove Categorical columns

X_train_num = X_train.drop(columns=['Gender', 'Location', 'GameGenre'])
X_test_num = X_test.drop(columns=['Gender', 'Location', 'GameGenre'])

In [ ]:
# OneHotEncoder returns Numpy not a DataFrame
# so , we have to join OHE columns

ohe_columns = ohe.get_feature_names_out(['Gender', 'Location', 'GameGenre'])
X_train_final  = pd.concat([X_train_num.reset_index(drop=True), pd.DataFrame(train_ohe, columns = ohe_columns)], axis=1)
X_test_final = pd.concat([X_test_num.reset_index(drop=True), pd.DataFrame(test_ohe, columns= ohe_columns)], axis=1)

In [ ]:
#Standard Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().set_output(transform='pandas')
X_train_scaled = scaler.fit_transform(X_train_final)
X_test_scaled = scaler.transform(X_test_final)

<h2> Calculate the sum of all the values present in first five rows of transformed test feature matrix ? (upto 2 digits afer the decimal)

In [ ]:
round(X_test_scaled.iloc[:4].sum().sum(), 2)

np.float64(-7.17)